### ISSUE TITLE
Feature Request: Ablity to install but disable extensions

### ISSUE THREAD

**Issue by binaryben** [zokugun/vscode-vsix-manager#10]
Sync Settings allows extensions to be installed but disabled. Can this please be supported with VSIX Manager as well? 

Proposal would be to keep the `vsix.extensions` setting which will install everything listed and add optional settings: `vsix.enabled` and `vsix.disabled`

The logic would be that if anything is listed in `vsix.enabled` then everything listed in `vsix.extensions` would be disabled if not listed in `vsix.enabled`. It should work the opposite way for `vsix.disabled`. Just an idea for possible workflow, open to other ideas.

**Comment by daiyam** [comment]
Maybe with a prefix like `-vsx:dev1.ext1`. It will avoid duplicates and easier to manage. What do you think?

**Comment by binaryben** [comment]
> Should the env variables be prefixed with `env.`?

Oh I didn't realise the env variables are all available as variables. Not sure where I saw the `env.-` used in relation to this but no, I don't think it's needed.

> Maybe adding the prefix existential operator (#if(?NODE_DEV))?

If this isn't already an option, it would be my preferred addition. I'll just need to know various environment variables exist to know which language extensions need switching on. I can use something like `#if(NODE_DEV='1')` though if needed.

```
   // enables only the wanted language
   // #rewrite-next-line
   // "#{DEV_LANG}",
```

Sorry, still not sure how that would allow me to enable for example, PHP, C#, Node and React extensions at the same time? That was the stack at my last workplace for example, and then I'd come home and use Nim, Node, Arduino and Vue.

**Comment by daiyam** [comment]
5 possibles ways to write:

1.
```
"vsix.extensions": [
   // #if (?NODE_DEV)
   "node",
   // else 
   "-node",
   // #endif
   // #if (?PYTHON_DEV)
   "python",
   // else 
   "-python",
   // #endif
],
```
2.
```
// disable all, enable only needed
"vsix.extensions.disabled": [
   "node",
   "python",
],
"vsix.extensions.enabled": [
   // #enable(?NODE_DEV)
   // "node",
   // #enable(?PYTHON_DEV)
   // "python",
],
```
3.
```
// enable all, disable not needed
"vsix.extensions.disabled": [
   // #enable(!?NODE_DEV)
   // "node",
   // #enable(!?PYTHON_DEV)
   // "python",
],
"vsix.extensions.enabled": [
   "node",
   "python",
],
```
4.
```
// disable all, enable only needed
"vsix.extensions": [
   "-node",
   "-python",
	
   // #enable(?NODE_DEV)
   // "node",
   // #enable(?PYTHON_DEV)
   // "python",
],
```
5.
```
// enable all, disable not needed
"vsix.extensions": [
   "node",
   "python",
	
   // #enable(!?NODE_DEV)
   // "-node",
   // #enable(!?PYTHON_DEV)
   // "-python",
],
```

I think 4. is the cleaner and clearest.

1. is a bit dirty
2. & 3. when reading, I asked myself, which block is done first
4. & 5. they are easiest to understand

**Comment by daiyam** [comment]
Can you try [vsix-manager-0.4.3.vsix](https://github.com/zokugun/vscode-vsix-manager/files/11006594/vsix-manager-0.4.3.vsix.zip)? (Uninstall the current one and **reload** VSCodium).

Here the few changes:
- enabling/disabling an extension requires that the editor is restarted.
- uninstalling an extension reloads the editor.
- the property `vsix.applyChanges` has been removed.

**Comment by binaryben** [comment]
**Here's what I've done:**

* Manually deleted all extensions except Sync Settings and Cron Tasks from `~/.vscode-oss/extensions`
* Restarted Codium
* Manually installed the VSIX you linked (nb. I had to remove the .zip extension for it to work and trying to install the extracted archive didn't work. Expected?)
* Edited my settings config to remove `vsix.applyChanges` config and to include a disabled extension defined as a basic object (see below)
* Ran the Sync Settings download command

```jsonc
      {
        "id": "vsx:DanielSanMedium.dscodegpt",
        "enabled": false
      },
```

**Here is what happened:**

* ✅ &nbsp; Extensions all started downloading
* ✅ &nbsp; MS extensions downloading without 429 errors
* ✅ &nbsp; Editor restarted once list of installed extensions was completed
* ✅ &nbsp; Code GPT extension was disabled once restarted as expected

**Yet to test or confirm:**

> enabling/disabling an extension requires that the editor is restarted.
> uninstalling an extension reloads the editor.

* Array syntax
* `?` and `!?` syntax
* #7 and #8

**Comment by daiyam** [comment]
> Can you please provide some more context on what is meant by enabling/disabling requires a restart? As in if I download settings that change the enabled flag, it will automatically restart?

There is no official API to enable or disable an extension from an extension. The only solution I found is to edit the sqlite db used by VSCode/VSCodium but the app needs to be restarted so that those changes are taken.
Yes, it will automatically restart the app when needed.

**Comment by daiyam** [comment]
> Random aside: esbenp.prettier-vscode and seatonjiang.gitmoji-vscode should use the same id on both marketplaces. They're marked as "not found" when trying to download through Open VSX though. The fallback worked and downloaded them for me from the official marketplace instead.

When querying with `esbenp.prettier-vscode`, OpenVSX find a bunch of extensions but not the correct one. Removing the dot seems to fix the issue.

**Comment by binaryben** [comment]
> There is no official API to enable or disable an extension from an extension. The only solution I found is to edit the sqlite db used by VSCode/VSCodium but the app needs to be restarted so that those changes are taken.
> Yes, it will automatically restart the app when needed.

In that case, that is working as expected

> When querying with `esbenp.prettier-vscode`, OpenVSX find a bunch of extensions but not the correct one. Removing the dot seems to fix the issue.

I think I'll just put those down to weird edge cases since the fallback works as expected. Thoughts?

**Comment by daiyam** [comment]
Here an updated version with fixes for `esbenp.prettier-vscode` and for the fallback to work even if there was any previous error.

[vsix-manager-0.4.3.vsix.zip](https://github.com/zokugun/vscode-vsix-manager/files/11008162/vsix-manager-0.4.3.vsix.zip)

**Comment by daiyam** [comment]
* [x] Array syntax
* [x] `?` and `!?` syntax

Both syntaxes are available.

**Comment by binaryben** [comment]
Array of ID's is not working as I'd expect it to. Here is my config:

```jsonc
"vsix.sources": {
    "local": {
      "type": "file",
      "path": "~/.files/config/editor/extensions"
    },
    "ms": {
      "type": "marketplace",
      "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery"
    },
    "vsx": {
      "type": "marketplace",
      // Set to the MS Marketplace URL to make vsx: ones fail
      "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery"
      // "serviceUrl": "https://open-vsx.org/vscode/gallery",
      // "fallback": "ms"
    }
  },
// ...
      {
        "id": [
          "vsx:hbenl.test-adapter-converter",
          "ms:ms-vscode.test-adapter-converter"
        ]
      },
// ...
      {
        "id": [
          "vsx:atlassian.atlascode",
          "ms:Atlassian.atlascode"
        ]
      },
// etc.
```

Here is the output:

```
...
installing extension: vsx:hbenl.test-adapter-converter
not found
...
installing extension: vsx:atlassian.atlascode
not found
installing extension: vsx:GitHub.vscode-pull-request-github
downloading version: 0.61.2023031710
Error: Unable to install extension 'github.vscode-pull-request-github' as it is not compatible with VS Code '1.76.2'
...
installing extension: vsx:Greenbyte.handlebars-preview
not found
...
installing extension: vsx:jeanp413.open-remote-ssh
not found
...
installing extension: vsx:codespaces-contrib.codeswing
not found
...
installing extension: vsx:Voklen.theme-by-language
not found
...
done
```

I'd expect it to start trying the next item in the `"id"` array?

**Comment by binaryben** [comment]
> Here an updated version with fixes for `esbenp.prettier-vscode` and for the fallback to work even if there was any previous error.

Yep, confirmed this is resolved with this version. Here is outcome of current manual tests:

* ✅  &nbsp; Extensions all started downloading on Setting Sync profile download
* ✅  &nbsp; MS extensions downloading without 429 errors
* ✅  &nbsp; Extensions disabled once restarted as expected
* ✅  &nbsp; Enabling/disabling/installing an extension restarts the editor
* ✅  &nbsp; #7
* ✅  &nbsp; #8
* ⚠️  &nbsp; Support string and object/array syntaxes
  * ✅  &nbsp; Support string syntax
  * ✅  &nbsp; Support object syntax
  * ❌  &nbsp; Support array syntax
* ❔ `?` and `!?` syntax (haven't tested but I'll assume it's working)

**Comment by daiyam** [comment]
> `?` and `!?` syntax (haven't tested but I'll assume it's working)

It should since they pass their unit tests

The following has the alternative extensions fixed (object syntax depends on that). (https://github.com/zokugun/vscode-vsix-manager/commit/7e3b98f42b19318f479e543378b1f80a27b0bb94)

[vsix-manager-0.4.3.vsix.zip](https://github.com/zokugun/vscode-vsix-manager/files/11008257/vsix-manager-0.4.3.vsix.zip)

I will need to add unit testing when I have some time...

**Comment by daiyam** [comment]
> * ✅    Enabling/disabling/installing an extension restarts the editor

`installing an extension` doesn't restart the editor. Only changing its state does.

**Comment by binaryben** [comment]
> `installing an extension` doesn't restart the editor. Only changing its state does.

Apologies, my misunderstanding.

> The following has the alternative extensions fixed

It certainly does! Thank you heaps. I've marked as closed - sorry if it's presumptuous

> I will need to add unit testing when I have some time...

Haha, no worries! Hope my manual testing helps guide that at least

**Comment by daiyam** [comment]
I forgot to publish a new version with the fixes :scream: :sob::sob:
