### ISSUE TITLE
Bug: Github source not working for zipped releases

### ISSUE THREAD

**Issue by binaryben** [zokugun/vscode-vsix-manager#11]
VSIX Manager is [checking the assets array for each release](https://github.com/zokugun/vscode-vsix-manager/blob/master/src/sources/github.ts#L37), but some publishers only release to Github via zipped/tarballed directories.

Can this extension download the zip release (`"zipball_url"`) if nothing meets the current criteria in the assets array and then check the contents of the archive for the vsix file to install?

Example repo: https://api.github.com/repos/sfccdevops/explorer-exclude-vscode-extension/releases

**Comment by daiyam** [comment]
:sob::sob::sob:

**Comment by daiyam** [comment]
Oh! This isn't a release! It just the source code of the extension which will need to be packaged. So I see no issue here.

**Comment by binaryben** [comment]
Ah, awkward! Sorry, I should have manually downloaded the zip myself and checked it contained the VSIX file. Definitely out of scope to expect VSIX manager to build it!
