### ISSUE TITLE
MS Marketplace

### ISSUE THREAD

**Issue by mbnoimi** [zokugun/vscode-vsix-manager#16]
May you please add an example for adding MS Marketplace in README file?

**Comment by mbnoimi** [comment]
I'm interesting in using GitHub copilot which is not available in [open-vsx.org](https://open-vsx.org/)

**Comment by tomByrer** [comment]
> I'm interesting in using GitHub copilot which is not available in [open-vsx.org](https://open-vsx.org/)

Ollama is able to be installed locally, though you need Apple M* chip, NVIDA GPU, or a strong CPU
https://open-vsx.org/extension/10nates/ollama-autocoder
