### ISSUE TITLE
Cannot install from file resource

### ISSUE THREAD

**Issue by Stephanevg** [zokugun/vscode-vsix-manager#21]
Hi,

I am trying to use your extension to install and manage extensions which are currently located locally on my server:

First, I was assuming I would be able to see the extensions that are listed in the extensions file path. I don't know if that is part of the extension, or if we can 'only' launch the installation of existing extensions based on the our settings.json. Could you clarify ?

There seems to be only linux examples. I am trying to use this on Windows, and I don't know if I am not correctly filling the Json files, OR if there is a bug.

This is my user settings.json file

```json
"vsix.sources": {
        "mfs": {
            "type": "file",
            "path": "C:\\Users\\Stephane\\Documents\\script-scripttemplate\\Sources\\scw-snippets\\",
        }
    },
    "vsix.debug": true,
    "vsix.extensions": [
        "scw-snippets-0.0.1"
    ],
```

>I tried using `\` `\\` `/` adding a slash and without at the end... My extension never showed up in the extension tab.

Nevertheless, when I do: `vsix Manager: Install extensions` I get the following error messages

But I do get the following message
![image](https://github.com/user-attachments/assets/6feebb49-1fc2-4d6b-bd71-1a8c44e7d800)

When I copy my extension manually to `C:\Users\MyUser\.vscode\extensions` It shows up.

- Question 2: Are 'Shares' supported ? (`\\MyServer123\MyExtensions\`) ?

**Comment by daiyam** [comment]
`"scw-snippets-0.0.1"` needs to be `"mfs:scw-snippets-0.0.1"` (prefixed with `mfs:`) so the extension knows which source to use.

> Question 2: Are 'Shares' supported ? (\\MyServer123\MyExtensions\) ?

It should be able but I haven't tested...

**Comment by Stephanevg** [comment]
Thanks for your quick answer. I didn't manage to make it work.
I am not sure if I have missed something in the configuration, or if there is a bug somewhere, as the only message I have, is the following one:

![image](https://github.com/user-attachments/assets/2989fe35-646d-4372-a4ee-e3913a2feacb)

It would be great to have little bit more information to help debug: 
Something like: 
```
Attempting installation from ${SnippetName}.
 [${vsix.SourceType}${SourceName}] Searching for ${$SnippetName} in ${$vsixSource.Path} 
 ```

I don't know if it is searching it in the right location. Can he access the folder structure or not ?
Can he find the vsix file, if not, what is the string he is actually searching for ?

My Vsix file Is called `scw-snippets-0.0.1.vsix` and located in `"C:\Users\Stephane\Documents\script-scripttemplate\Sources\scw-snippets\"`

This is what my `settings.json` looks like:

```Json
"vsix.sources": {
        "mfs": {
            "type": "file",
            "path": "C:/Users/adm1-taavast3/Documents/script-scripttemplate/Sources/scw-snippets",
        }
    },
    "vsix.debug": true,
    "vsix.extensions": [
        "mfs:Swisscom-Common-Team.scw-snippets-0.0.1"
    ],
```

**Comment by daiyam** [comment]
The version can be omitted since you can have several versions in same folder and the manager always picks the newest version.

**Comment by Stephanevg** [comment]
ok, removing the version actually solve it. I could install it successfully now using the command `VSIX Manager: Install extensions`

![image](https://github.com/user-attachments/assets/49e101ea-1d2f-4697-ad56-e6c8e7d8e3d6)

Is there no way to have the extensions that we specifiy in the vsix.extensions visbile in the extension pane __before__ we install them ?
So that the user can choose pick and choose using the GUI ?

**Comment by daiyam** [comment]
> Is there no way to have the extensions that we specifiy in the vsix.extensions visbile in the extension pane **before** we install them ? So that the user can choose pick and choose using the GUI ?

No, it's not possible. I've check if there was new commands available to do that.

The user can comment the line of the extensions he don't want.

**Comment by Stephanevg** [comment]
ok. Great. Thanks a lot for you answers @daiyam ! :)

**Comment by daiyam** [comment]
I've improved the doc, hopefully it will good enough ;)
