### ISSUE TITLE
Feature Request: Fallback to different marketplace

### ISSUE THREAD

**Issue by binaryben** [zokugun/vscode-vsix-manager#8]
Open VSX has been very unreliable for me. Is it possible to make it so a source could have a fallback? I am imaging something like this:

```jsonc
"vsix.sources": {
    "ms": {
      "type": "marketplace",
      "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery"
    },
    "local": {
      "type": "file",
      "path": "~/.files/config/editor/extensions",
      "fallback": "ms"
    },
    "vsx": {
      "type": "marketplace",
      "serviceUrl": "https://open-vsx.org/vscode/gallery",
      "serviceFallback": "ms"
    }
}
```

The only caveat is that extensions might need to support fallback overrides - that is to solve part of the original issue of having different ID's on different marketplaces

**Comment by daiyam** [comment]
Just `"fallback": "ms"` will be fine.

Maybe adding an alternate to a extension like `vsx:dev1.ext1|ms:dev2.ext2`. Install `dev2.ext2` from `ms` if `dev1.ext1` isn't found.

**Comment by binaryben** [comment]
Sounds good! Adding a list of alternatives as an array might be easier to read? But I have no preference.

```jsonc
"vsix.extensions": [
  "group",
  "vsx:devX.extX",
  [ // Note: devX has different id on Open VSX
    "vsx:devXalt.extYalt",
    "ms:devX.extY"
  ]
],
```

**Comment by daiyam** [comment]
How to disable?
```
{
  "id": [ // Note: devX has different id on Open VSX
    "vsx:devXalt.extYalt",
    "ms:devX.extY"
  ],
  "disabled": true
}
```
```
-vsx:dev1.ext1|ms:dev2.ext2
```
```
- vsx:dev1.ext1 || ms:dev2.ext2
```

**Comment by binaryben** [comment]
See #10 for context but I think first option you posted is best.
