### ISSUE TITLE
Bug: Getting "already installed" when extension isn't installed

### ISSUE THREAD

**Issue by binaryben** [zokugun/vscode-vsix-manager#9]
Not sure how to debug this properly for you or give any more context - this is all the output given:

> installing extension: vsx:yzhang.markdown-all-in-one
> already installed

Not just this extension, it happens seemingly at random. Something seems to be amiss with the state management

**Comment by binaryben** [comment]
For anyone getting similar issues, deleting the `~/.vscode[-oss]/extensions` directory and starting again resolves these inconsistencies. Not sure what the root issue is though

**Comment by GitMensch** [comment]
Could you reproduce it and give steps to do so?

**Comment by daiyam** [comment]
I think the `v0.5.0` should have fixed the issue.
